image: gitlab/dind:latest

stages:
- build
- push

variables:
  TRACE: TRACE

build:
  only:
  - tags
  - develop
  stage: build
  before_script:
  - echo 1 | tee /proc/sys/net/ipv6/conf/all/forwarding | /proc/sys/net/ipv6/conf/default/forwarding
  - ip6tables -t nat -A POSTROUTING -o eth0 -s fde4:e91:816d:2::/64 -j MASQUERADE 
  - ip route del default
  - ip -o -4 a s eth0 | while read line; do echo $line | awk '{print "ip addr del " $4 " dev " $2 }' | sh -x; done
  script:
  - docker build -t virt-manager .
  
release:
  stage: push
  only:
  - tags
  before_script:
  - ip route del default
  - ip -o -4 a s eth0 | while read line; do echo $line | awk '{print "ip addr del " $4 " dev " $2 }' | sh -x; done
  - docker login -t $DOCKER_USER -p $DOCKER_PASSWORD
  script:
  - docker tag virt-manager $DOCKER_USER/virt-manager
  - docker push $DOCKER_USER/virt-manager
  after_script:
  - docker logout